server:
  port: 8089
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    #allow-redirects: true
#    register-with-eureka: true
#    fetch-registry: true
#    service-url: http://localhost:8761/eureka/